### ISSUE TITLE
Unable to sort convictions for cases with missing dispositions

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/recordexpungPDX#291]
## Description
Unable to sort conviction charges, because one of the dates is a string. Closed cases with partial dispositions are creating charges that do not have a disposition

### Current behavior
The current behavior is that charges for without a disposition are being marked as missing disposition and are being skipped in the expungement process, however this is only working when a case does not have any disposition transactions.

See PR #255 for when this behavior was added.

### Expected behavior
Any charge that does not have a disposition should be skipped regardless if the case has disposition transactions. This is needed for closed cases that have disposition transactions for some, but not all charges.

### Stack trace
```
Traceback (most recent call last):
  File "cli.py", line 117, in <module>
    expunged = expunger.run()
  File "/recordexpungPDX/src/backend/expungeservice/expunger/expunger.py", line 55, in run
    self._set_most_recent_convictions()
  File "/recordexpungPDX/src/backend/expungeservice/expunger/expunger.py", line 94, in _set_most_recent_convictions
    self.convictions.sort(key=lambda charge: charge.disposition.date)
TypeError: '<' not supported between instances of 'str' and 'datetime.date'
```

### Possible fix:
One issue is that there is a mutable default in the base_charge initializer.
https://github.com/codeforpdx/recordexpungPDX/blob/master/src/backend/expungeservice/models/charge_types/base_charge.py#L12
This should be replaced with None and then add a guard for creating a disposition.

### This task is done when:
 - Use case fixture 'CASE_WITH_PARTIAL_DISPOS` to create a system test that exposes bug
 - Create unit test that also exposes bug
 - Any charges that do not have dispositions should be tagged as such and skipped by the time analysis.

**Comment by NickSchimek** [comment]
This still needs to be fixed. It fails for when there is a case without dispositions, and not all closed charges without a disposition are being marked as "Needs further attention"
